### PR TITLE
WIP: Rewrite frontend using React

### PR DESCRIPTION
**Pull request by danielwrobert**
Getting the basic project setup and integrated into the existing structure. Not ready to merge yet but making a PR for tracking and communication.

I added to the v3 Milestone because I wasn't sure where to put it. The final product may take a bit longer before it's ready for "launch".

### CODE REVIEW

**Comment by danielwrobert** [comment]
Currently I've set up a "Hello World"-like component with React that renders on the front page.

I've included Babel to transpile the ES6 code to ES5. The issue was that I wasn't considering it _still_ needed to be bundled to code that can be read by the browser. As a quick, temporary solution, I added an NPM script to handle that. The downside is that you first have to run the Gulp task to transpile and _then_ run the NPM task afterwards to serve to the browser. But this is just a temp fix ... I will circle back and implement one of the two approaches:

1. Move the NPM task into the Gulp process
1. Migrate the whole build process over to Webpack

If I move the the NPM task to Gulp, we'll need to install Browserify, Babelify, Watchify, etc. We'll need to modify the build tasks quite a bit with an approach similar to [this example](http://mikevalstar.com/post/fast-gulp-browserify-babelify-watchify-react-build/). If this is really the best/easiest approach, then I'm fine with that. I'm leaning towards the latter of the two options, however.

If we move to Webpack, I think we can slim down a lot of the dependencies, as Webpack handles the Browserify (and friends) job as well as all of the other Gulp tasks we need. In addition, it seems to be the standard tool used (probably for that very reason) by people building React apps, both within and outside of the company. If I understand correctly, Webpack also allows you to modularize your code (including your CSS) in a way that the other approach does not.

Before jumping on the Webpack wagon, I want to make sure we can handle all of the existing tasks we're using in the Gulp build. I know for sure we can compile the Sass and I'm 99.99% sure there's an SVG loader as well.

**Comment by michiecat** [comment]
We discussed this a bit today and the consensus was that moving to Webpack sounds like a good idea, as long as we'll be able to do everything we need to do with SVGs (which it sounds like we can)? There will be further discussion but overall this looks like a go.

**Comment by danielwrobert** [comment]
I've replaced Gulp with Webpack on this branch. One thing to note is that the Node dependencies have changed quite a bit between the two branches.

If you want to run this branch, you will need to remove your `node_modules` directory and run `npm install` again. If you don't want to have to do this every time you switch branches, you can clone a separate local environment and run this branch separately there for testing. The `node_modules` directory is not tracked by Git so that is why they need to be swapped manually. See Slack channel for conversation/context.

Once you have everything set up on this branch, you can run `npm start` to initialize the Webpack watch task.

This includes a SVG and image optimize loader, as well as [PostCSS SVG Fragments](https://github.com/jonathantneal/postcss-svg-fragments). We will probably need to include a SVG sprite loader, based on what @sarahmonster mentioned. [This one](https://github.com/kisenka/svg-sprite-loader) may be what we're looking for. @sarahmonster let me know if that fits what you are wanting to achieve! :)

**Comment by sarahmonster** [comment]
Re-running `npm install` makes perfect sense to me—tracking node modules would be utter madness, and I still think it's best to keep this change as a branch, rather than an entirely new repo.

Given that this is mostly front-end and (in theory) our data will remain the same, the fastest way to swap between branches is likely by cloning the rep into a new `themes/` directory:

```
git clone git@github.com:a8cteam51/strikebase.git strikebase-react
cd strikebase-react
git checkout update/react-frontend
```

and then:
`wp theme activate strikebase-react`

**Comment by sarahmonster** [comment]
As far as SVG is concerned, let's not worry about this just yet, until we're ready to actually implement front-end icons. If the icons are included as React components (which is likely the method I'd lean toward, but I'd need to look into it more once we've actually got some icons ready to go), React will basically take care of the caching for us, so we don't need to worry about the same things we do with a vanilla HTML frontend.

Further reading: https://css-tricks.com/creating-svg-icon-system-react/

**Comment by danielwrobert** [comment]
> the fastest way to swap between branches is likely by cloning the rep into a new `themes/` directory

**Comment by danielwrobert** [comment]
> the fastest way to swap between branches is likely by cloning the rep into a new `themes/` directory

Yeah, this is basically what we decided on in the Slack channel. Although, when I set this up locally I created a separate WP install in case I needed to test some separate data for whatever reason. Cloning to a separate theme probably makes more sense though. I'll likely switch to that, now that I have the first steps squared away.

With regards to the SVGs, that sounds good to me! I read that article you linked a while back and I think that could be a nice approach to consider depending on how we decide to use the icons, and since we're already using React here. If we just want to set them as background images, one of the PostCSS plugins may be faster to implement. Either way, we can discuss more when we get to that point!

**Comment by sarahmonster** [comment]
I'm not a big fan of SVGs as background images, mostly because you can't access them to style them via CSS directly, and you've got to rely on hacks. Inline you've got direct control. But we'll stick with what we have right now and I can mess around with it once we're further along with things.

**Comment by danielwrobert** [comment]
This is being developed in a separate repository. Closing this PR here.

**Pull request closed without merging**
