### PR TITLE
Add/custom fields

### PR DESCRIPTION
**Pull request by danielwrobert**
The following updates are in this branch to be merged:

1. Added Custom Fields for People CPT
1. Added Custom Fields for Projects CPT
1. Re-arranged CPT file/project structure based on our prior discussion

### CODE REVIEW

**Comment by danielwrobert** [comment]
The only thing I did _not_ set up was, in the Projects Custom Fields, the first two items (strikers and influencers) are not "connected" to the Person CPT. I'm not clear on what you mean by that so I'm not sure how to best go about it at this point. Perhaps a taxonomy relation of some sort? I figure we can easily circle back to that and link things up where or how ever we need.

Fixes #7 

Fixes #11

**Comment by sarahmonster** [comment]
I've made some minor copyedits to the labels and rebased on master. Since this is dependent on a plugin (it took me a while to figure out why that wasn't working properly), I've also added the code to load the plugin in a VIP context as well, so it should show up on the production site without requiring any extra manual work.

A few initial thoughts:
- "timezone" might work nicely as a drop-down, to ensure normalisation across entries
- entering social media accounts in a free-form textarea feels laborious (plus do we separate them by newline, or by comma?)... I'd be tempted to think a series of + drop-downs (so "add new social media account" to add x number of repeatable fields and then a drop-down to select the network, plus an input box for the username [described poorly but I can mock up what I mean]) might work better here, but that's probably a v2 feature and would require @michiecat's input anyway
- we'll need to discuss how best to connect people to projects (see #12) ... maybe a drop-down under the "people" section of the "add project" interface?
- for URLs, can we autofill with an http:// to avoid that extra legwork? (Actually if we could auto-fill contextually, like "https://github.com/a8cteam51/" for the "code repository" input, that would be even easier/faster!)
- we'll need to add these fields to the front-end display as well (#20)

**Comment by danielwrobert** [comment]
> I've made some minor copyedits to the labels and rebased on master.

Sounds good! Should this be merged then or is there something I still need to do?

> Since this is dependent on a plugin (it took me a while to figure out why that wasn't working properly), I've also added the code to load the plugin in a VIP context as well, so it should show up on the production site without requiring any extra manual work.

Oh, sorry about that. I should have mentioned it, I just thought we discussed the plugin already for some reason. My mistake!

I like your additional thoughts! Things to look into and I'm sure we can figure those out. 

> for URLs, can we autofill with an http:// to avoid that extra legwork? (Actually if we could auto-fill contextually, like "https://github.com/a8cteam51/" for the "code repository" input, that would be even easier/faster!)

Oh, there are actually link fields in FieldManager. I should have set those up that way, I just set them up literally in line with how you listed them out as an item. That's an easy thing to switch though. We'll just need to sync up and decide which inputs need to be link fields. Then I can swap those over.

**Comment by sarahmonster** [comment]
I've changed the link inputs to URL inputs; unfortunately that doesn't auto-populate the field but I'll split that into a separate issue, along with some other UI improvements. Merging & deploying to master now. 👍

**Pull request merged**
