### PR TITLE
Add filtering functionality to projects and people views

### LINKED ISSUE #96: jQuery component: filters
In the interests of making our v2 deadline, I'm going to build out a transitional filtering component using jQuery. We've pushed the React component (#84) to v3 and we'll use this in the meantime.

@sarahmonster provided HTML/CSS in #48, and worked out hierarchical menu drop-downs in #95. We now just need to show/hide the cards as needed, and provide visual indicators for when an element is selected. (Designs in #48.)

We may want to apply filters to the default view as well—I think "type: influencer" for people, and "status: active" for projects.

### PR DESCRIPTION
**Pull request by sarahmonster**
This is branched from #95. Once that's merged this will be much quicker/easier to review. I'm trying to use stacked PRs to keep sizes manageable.

This is what I ended up with with the filters:
go-filters

It's not 100% perfect but it's good enough to use. I tried getting some complex show/hide animations happening but I think that's going to be best saved for later, particularly since we'll be largely rebuilding this functionality anyway.

Closes #96.

### CODE REVIEW

**Comment by michiecat** [comment]
Worked well when I tested it, nice work. :) I actually prefer it without an animation at this point because it's quick and snappy.

**Comment by sarahmonster** [comment]
A little animation on show/hide would help make it obvious something has changed—sometimes it isn't super obvious something's changed, because it happens immediately and the cards (currently) aren't very distinct from one another. (Try "consulting" under "project type", for instance!)

It'd need to be super fast, but enough to make it more clear that a change has happened. Investing time in getting it right now doesn't make sense since it's only a prototype, but once we're into the React version I'll do an animation audit to make everything feel a bit smoother.

**Comment by michiecat** [comment]
Sounds good to me. Yes, I agree that a quick & sweet animation would be nice to have for the reasons you gave, but it's certainly not necessary at this point and good to add to the React version in the future. Definitely on board with keeping the animation quick and something that wouldn't tire us out on repeated usage.

If @danielwrobert doesn't have any objections we can go ahead and merge this.

**Comment by sarahmonster** [comment]
> The only thing we/I will need to be sure to do is to comment out or remove the following items, when merging with the Redux branch

That's because we'll need to rebuild those pieces, right? It'd be nice if some of it might be reusable, but I'm not super attached. 😜 I left the console.logs in there mostly because it's super helpful if you're debugging (the code is a bit of if/else soup and the functionality doesn't work perfectly) and I just figured I'd leave them in case they'd be future-helpful as well, but I'm okay with removing if it makes more sense.

**Comment by danielwrobert** [comment]
> It'd be nice if some of it might be reusable, but I'm not super attached.

I'll definitely look into what can be reused when I go about adding this functionality to the React version. I agree, it would be great if I can pull at least some of it out. It's quite a different approach to jQuery, regarding functionality, but maybe/hopefully the structure and styles can remain the same.

**Pull request merged**
