### PR TITLE
Restructure custom content types.

### PR DESCRIPTION
**Pull request by danielwrobert**
Here's what I did:

- I moved all of the content types out into their own directories, separating Custom Fields, Taxonomies, and Post Types.
- Each file/class is named according to it's content type.
- The custom taxonomies are grouped by associated post type. Taxonomies that are shared across multiple post types are grouped in a `Strikebase_Taxonomies_Shared` class. Since there are many different custom fields and _most_ seem to be linked to one CPT at a time, this seemed to be the most sensible way to split up the section.
- Set up an abstract singleton class to extend from for each new content type. This forces certain methods to be called, while also only allowing for once instance of each child class (content type class) to be instantiated.
- Registered each content type from a register file in the content type directory. This cleans up the `functions.php` file a good amount because you only need to include one file for each content type.

Any new content types will be able to be added via extending the abstract parent class and then registered with the type's register file.

I hope that's sensible. I know it's a lot of restructure for that section but I think it will make adding new custom content types and maintaining the existing ones much more manageable going forward.

I tested these changes out on the front end and via the WP-Admin and everything seems to be working as expected.

### CODE REVIEW

**Comment by sarahmonster** [comment]
I wonder if we can simplify the naming of the files. I get the desire to be verbose and explicit, but I think it might be adding unnecessary complexity without any real gain—if I open the file I know it's a class.

This is my complaint:
screenshot 2017-01-27 18 54 27

I can't really tell which file I'm opening or switching to from my editor tabs or sidebar, because the names are too long and they all have the same prefix. This has already lead to me opening the wrong files a few times.

**Comment by danielwrobert** [comment]
Last commit wasn't so much a correction of a syntax error but a property misnaming.

@sarahmonster Yes, I think it would be sufficient enough to remove the `class-strikebase-` from the file names. Like you said, you open the file, you know it's a class. Also the class names are prefixed, I don't think the file names need to be as well. I will adjust.

**Comment by danielwrobert** [comment]
Ok, I updated the file names. I think that they're just as sensible now but not as verbose. Note that I did keep the `class-` prefix on the class files. This appears to be a convention in WP, looking at some of the Core files. For example, see `wp-admin/includes/`. All of the class files there are prefixed that way. I did remove the theme name prefix to the filename though and the word `custom` on every file. So it is still less verbose. I'm hoping I found a happy medium!

**Comment by sarahmonster** [comment]
Definitely better. They do still get cut off a bit:
screenshot 2017-01-30 16 28 48

Using the Jetpack syntax of `class.whatever` rather than `class-whatever` may help a bit here. What about inversing the order as well, so instead of `class-post-type-person` it's `class.person-post-type`?

**Comment by danielwrobert** [comment]
I think it was absolutely sensible to remove the theme name prefix because that really has no good reason to be in there and the names were unnecessarily verbose. I think the way it is now, however, makes sense and it's going along with core's approach to class naming in files.

It's worth noting that, if you go into enough directories or depending on your viewport size, the filenames will get cut off art _some_ point anyway. Which is probably why you can horizontally scroll or adjust the width of your file drawer. Even if you look at Jetpack's files [here](https://github.com/Automattic/jetpack), many of the class file names are getting clipped. Probably more so, if you viewed in your editor. I'd personally rather have a sensible convention than worry too much about them getting cut off in the file names in the file drawer.

That said, I think the Jetpack approach with the`.` instead of the `-` after `class` would be totally fine, too, if you think it will make a difference!

The reason I named the files in that order is because the names for the child classes are just being appended to "parent" Abstract filename. So the parent Abstract class for Post Types is the `class-post-type`. The children classes that extend that class are `class-post-type-person` and `class-post-type-project`. So it seems sensible to append the name of the extending class at the end that way.

I also still have to update/add comments in the file files before we merge anything so I'll try to get to that today!

**Pull request merged**
