### PR TITLE
Implement hierarchical filter drop-downs.

### PR DESCRIPTION
**Pull request by sarahmonster**
This ended up being a more complex PR than I'd originally intended, but it turns out it was a bit more complex to get everything right.

filter-hierarchy

Basically, this adds hierarchical structure to the filter menus, which keeps things from getting too unwieldy. (See #94 for a bit of discussion here.) Originally I was only thinking we'd use it for the genre, but I think it could be useful for hosts as well, since we could then group all the individual third-party hosts under "self-hosted".

screenshot 2017-03-09 17 40 15

(Side note: @michiecat what is WordPress.com Enterprise?)

Icons are placeholders for the moment, until I start working on #74—they'll be more elegant once I've put together a proper icon set. 

The filters themselves aren't working just yet—I'm going to work on those in a separate PR, to keep things from getting out of hand here. 

Things to review here: is the code okay? Are the drop-downs intuitive to use? Are we going to have issues porting the jQuery here over to the React version?

### CODE REVIEW

**Comment by michiecat** [comment]
I love this! It worked as expected in my testing, let me know if there is anything in particular that you'd like to test aside from general functionality. :)

Agreed on using hierarchies for hosts, so we don't end up with a super long list to filter. :) We could even group the wpcom platforms together, if we think that makes sense.

>(Side note: @michiecat what is WordPress.com Enterprise?
WordPress.com Enterprise was a mid-level version of wpcom halfway between VIP and regular wpcom; it allowed for custom CSS, JS, and access to VIP plugins. It was retired in 2015 (closed to new sign-ups) but we have a couple of clients still on it.

**Comment by sarahmonster** [comment]
> The only snitch: when you click on a parent item, it doesn't slide to reveal the child item unless you click the arrow itself. If you click anywhere else, the dropdown vanishes. Although I assume that's intended behavior since we still want to be able to filter by the parent item, too.

That was the original intended behaviour, but I tested it (on myself and on @tofumatt) and found it awkward (like you). It's actually fixed in #97, which I think feels like more natural behaviour. 

If we find that we need the ability to quickly show all in a parent filter, we can add that functionality later. It will require some extra machinations (filtering post class to add parent categories etc) so best left for the final implementation unless it's critical for our use right now. 

From a UI perspective, I think it makes most sense to show a "view all in this category" link under the submenu along with the other sub-items. For the moment, you can accomplish this by selecting all filters within the sub-menu—so it's still doable, just requires a bit more legwork.

**Comment by michiecat** [comment]
Yes, I like the way it works in #97, which definitely feels more natural. What you have is good for now. It doesn't make sense to build the "View All" functionality when we don't know if it's something we'll need at this point. Keeping our category lists short and tight will also help. :)

**Comment by sarahmonster** [comment]
These changed were already merged in with #97, so I'm closing this!

**Pull request closed without merging**
