### PR TITLE
Implement basic responsive behaviour.

### PR DESCRIPTION
**Pull request by sarahmonster**
This sets up the basic responsive behaviour of the site structure—primarily displaying two columns of content when we're on a larger screen, and splitting table rows into distinct lines (or hiding columns?) on smaller screens.

Two-column layout is done but I still need to work on making the archive/listing tables responsive.

Tagging this v2 since it's technically not required for a v1. :)

### CODE REVIEW

**Comment by sarahmonster** [comment]
Responsible tables are now done (I've stacked them)... marking this branch needs-review as it's ready to merge now.

**Comment by michiecat** [comment]
Looks great to me, love the responsive styles so far!

**Comment by michiecat** [comment]
One thing I noticed: on mobile, I think it would be better if the projects were displayed inline (as a comma-separated list after "Projects") for space-saving purposes: 

https://cloudup.com/cSULwwJ2F8h

**Comment by sarahmonster** [comment]
This is actually an inconsistency issue with the way that projects-attached-to-people were implemented:

screenshot 2016-11-07 12 38 12

I think it'd make sense to use commas consistently throughout, or at least decide on a consistent approach for both here. Let's tackle this in #52.

**Comment by sarahmonster** [comment]
On second thought, I think the better solution here would be to have both orgs and projects on new lines at desktop sizes, and then comma-separated at smaller sizes. 

I've already cleaned up the template tags for this in #53; once either this branch or that branch is merged I can update the rules to add the responsive behaviour.

**Comment by danielwrobert** [comment]
Looks good to me! Merging ...

**Pull request merged**
